# -*- coding: utf-8 -*-
"""Tarea1_POO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqdqcuX0PaAepLBwuRlMsPdiRp_hqs9w

## Punto 1
"""

# Solucion punto 1
def sumaDigitos(): # Dado un número entero, calcula la suma de todos sus dígitos.

    numero = int(input("Ingrese un número: "))
    suma = 0
    while numero > 0:
        suma += numero % 10 #
        numero //= 10
    print("La suma de los dígitos es:", suma)
    print("\n")

# Solucion punto 1
def contarVocales(): # Dada una cadena de texto, cuenta el número de vocales (a, e, i, o, u, sin distinguir mayúsculas de minúsculas) que contiene.

  cadena = input("Ingrese una cadena de texto para contar las vocales: ")
  total = 0
  for letra in cadena:
    if letra == 'a' or letra == 'e' or letra == 'i' or letra == 'o' or letra == 'u':
      total += 1
    if letra == 'A' or letra == 'E' or letra == 'I' or letra == 'O' or letra == 'U':
      total += 1
  print("La cantidad de vocales que hay es: ", total)
  print("\n")




def verificarPalindromo(): # Determina si una cadena de texto es un palíndromo, es decir, se lee igual de izquierda a derecha que de derecha a izquierda.

  cadena = input("Ingrese una cadena de texto para saber si es un palindromo: ")
  if cadena == cadena[::-1]:
    print("Es un palíndromo")
  else:
    print("No es un palíndromo")
  print("\n")



def invertirListas(): # Dada una lista de números enteros separados por espacios, invierte el orden de los elementos y muestra la lista invertida en una sola línea.

  lista = []
  n = int(input("Ingrese el tamaño de la lista: "))
  for i in range(n):
    lista.append(int(input("Ingrese un número: "))) # agregar elementos a la lista
  print("La lista es:", " ".join(map(str, lista))) # imprimir la lista original
  listaInvertida = lista[::-1] # se invierte la lista
  print("La lista invertida es:", " ".join(map(str, listaInvertida)))
  print("\n")



def contarPalabras(): # Dada una cadena de texto, cuenta la cantidad de palabras que contiene. Se asume que las palabras están separadas por uno o más espacios.

  cadena = input("Ingrese una cadena de texto: ")
  palabras = cadena.split()
  print("El número de palabras es:", len(palabras))
  print("\n")



def maxOmin(): # Dada una lista de números enteros separados por espacios, determina cuál es el número mayor y cuál es el menor.
  numeros = []
  n = int(input("Ingrese la cantidad de numeros que desea ingresar a la lista: "))
  for i in range(n):
    numeros.append(int(input("Ingrese un número: ")))

  print("El número mayor es:", max(numeros))
  print("El número menor es:", min(numeros))
  print("\n")


#____________________________________________________________________________

print("\n____Bienvenido a la Tarea #1 de Juana:___\n")

while opcion != "0":

  print("\nSeleccione el punto que desea ejecutar:")
  print("1 - Suma de Dígitos")
  print("2 - Contar Vocales")
  print("3 - Verificar Palíndromo")
  print("4 - Invertir Lista")
  print("5 - Contar Palabras")
  print("6 - Máximo y Mínimo")
  print("0 - Salir")
  opcion = input("Opción: ")

  if opcion == "1":
    sumaDigitos()
  elif opcion == "2":
    contarVocales()
  elif opcion == "3":
    verificarPalindromo()
  elif opcion == "4":
    invertirListas()
  elif opcion == "5":
    contarPalabras()
  elif opcion == "6":
    maxOmin()
  elif opcion == "0":
    print("Bye bye bye ... ")
  else:
    print("Opción no válida, intente de nuevo.")